---

- include: packages.yml
  when: ansible_os_family == "Debian" and backup_jobs is defined
  tags: [ 'backup_packages' ]

- include: configure.yml
  when: backup_jobs is defined
  tags: [ 'backup_configure' ]
